modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory

license="All rights reserved" #mandatory

[[mods]] #mandatory

modId="molomenumod" #mandatory

version="SNAPSHOT 1.0" #mandatory

displayName="MoloMenuMod" #mandatory

logoFile="molomenulogo.png" #mandatory

credits="Thanks for download this mod!" #mandatory

authors="Author - Molodec_KDR." #mandatory

description= '''

Sample Text

'''
[[dependencies.molomenumod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.molomenumod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
